echo $PPID > router_processes.txt
python routing_node_server.py router0 &
echo $! >> router_processes.txt
python routing_node_server.py router1 &
echo $! >> router_processes.txt
python routing_node_server.py router2 &
echo $! >> router_processes.txt
python routing_node_server.py router3 &
echo $! >> router_processes.txt
python routing_node_server.py router4 &
echo $! >> router_processes.txt