echo $PPID > router_processes.txt
python run_server_node.py ../routingnode/cred_router0.txt &
echo $! >> router_processes.txt
python run_server_node.py ../routingnode/cred_router1.txt &
echo $! >> router_processes.txt
python run_server_node.py ../routingnode/cred_router2.txt &
echo $! >> router_processes.txt
python run_server_node.py ../routingnode/cred_router3.txt &
echo $! >> router_processes.txt
python run_server_node.py ../routingnode/cred_router4.txt &
echo $! >> router_processes.txt
